# Generated by Django 2.2.1 on 2019-10-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appceo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appceo',
            new_name='appceo_data',
        ),
    ]
