# Generated by Django 2.2.1 on 2019-10-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appceo', '0003_appceo_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appceo_data',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
